### ISSUE TITLE
$raw support numbered indexes for ramda

### ISSUE THREAD

**Issue by paul-sachs** [bsalex/typed-path#10]
Currently, using an index field with ramda can cause some confusion:

```ts
tp<typeof state>().array[index].x.y.$raw
```

This produces a path of ['array', index.toString(), 'x', 'y']. This causes problems in ramda since it looks to the path type to determine array or object. This will cause something like `assocPath` to turn an array into an object.

**Comment by paul-sachs** [comment]
I believe a simple fix to this line would do:

https://github.com/bsalex/typed-path/blob/271f283b1cedc07f5c257ea070115b230a28b32b/index.ts#L61

Changing it to something like:

```ts
return typedPath(handlersConfig, [...path, (typeof name === 'number' ? name : name.toString())], true);
```

This would break some typing currently in place but would also make sure we support ramda properly.

**Comment by bsalex** [comment]
Hi @paul-sachs 
Thanks for the report.

I've added another default handler, `.$rawPath`, to keep backward compatibility. 
Could you try your scenario with version `typed-path@2.2.0-beta.0` and `.$rawPath`?

**Comment by paul-sachs** [comment]
@bsalex Yeah I'll give it a shot in the next few days. Thanks for the quick response.

**Comment by paul-sachs** [comment]
@bsalex looks better. I think my version of ramda has problems with the `(string | number | symbol)[]` bit though, works fine with `(string | number)[]`. Might just my version of ramda types though (@types/ramda@0.26.18) so I can work around that with a simple cast.

**Comment by bsalex** [comment]
@paul-sachs 
Thanks.

Could you clarify whether the changes in the `2.2.0-beta.0` fixed the issue you have with `ramda` (with the workaround)?
The goal is to push the changes to the public package if they help.

Also, it would be great to add documentation for a simple use case with `ramda`.
Could you share an example for the issue that you've encountered?

**Comment by paul-sachs** [comment]
@bsalex yeah, i'll write something up shortly. My example is pretty nested in an application so I'll simplify and put something together.

**Comment by paul-sachs** [comment]
@bsalex I've created a simple codesandbox to show the issue: https://codesandbox.io/s/thirsty-sunset-q85b2?file=/src/App.tsx

You can see the change in array status if you switch to an older version of typed-path (and replace $rawPath with $raw)

**Comment by bsalex** [comment]
Thanks for the contribution,
typed-path@2.2.0 has been published
https://www.npmjs.com/package/typed-path

**Comment by bsalex** [comment]
I'm closing the issue, thanks again for the report.
Feel free to open another issue if you encounter a problem.
