### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by eirikb** [bsalex/typed-path#14]
Hi

What is the browser support here?  
I noticed it uses `Proxy`, so I suspect **IE11** is out of the picture?  
Ref https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#browser_compatibility

**Comment by bsalex** [comment]
Hi
Yes, IE11 is not supported in the current implementation.

**Comment by eirikb** [comment]
Ok. Thanks.
