### ISSUE TITLE
How to define typedPath return type?  

### ISSUE THREAD

**Issue by ALEUT** [bsalex/typed-path#23]
Hi!

I need to define generic return type of ```typedPath``` function. I see it returns ```TypedPathWrapper```, which mentions ```DefaultHandlers```. I tried ```ReturnType<typeof typedPath>```, but in this case it's not generic and displayed as ```any```. If I use ```TypedPathWrapper``` - it requires 2 options, first is type itself and second is handlers. But if I use default handlers, I need ```DefaultHandlers```, but it's not explorted. I suggest to export ```DefaultHandlers```. Currently I use it like ```export type TPWrapper<T> = TypedPathWrapper<DeepRequired<T>, any>;```

**Comment by bsalex** [comment]
Hi! 
Thank you for the feedback.

Could you provide more details on the issue? 
It would be great to see a Typescript code sample. 
You can start by forking this sandbox - https://codesandbox.io/s/typed-path-ramda-assoc-path-x3qby?file=/src/index.ts

The sample will help contributors to understand what is the desired behavior and could be included in the documentation.

**Comment by ALEUT** [comment]
Hi!

I use ```TypedPathWrapper``` like this one:
```export type TPWrapper<T> = TypedPathWrapper<T, any>; // TODO: replace any with DefaultHandlers when possible```
```
interface Props {
  readonly recordsPath?: TPWrapper<PhysicalRule[] | undefined>;
}
```

So I suggest just to fix:
```export type DefaultHandlers = typeof defaultHandlersConfig;```
