### ISSUE TITLE
Support optional properties.

### ISSUE THREAD

**Issue by WestonThayer** [bsalex/typed-path#7]
It's common for properties of Typescript interfaces to be optional:

```ts
interface Thing {
  foo: string;
  bar?: string;
}
```

`typedPath<Thing>().bar.$path` raises an `Object is possibly 'undefined'` error, when that's probably not desireable.

**Comment by bsalex** [comment]
Hi @WestonThayer.
Could you try the latest version?
Here is the test that is passing: https://github.com/bsalex/typed-path/blob/3d46b6eb75705b129df8dd1bef330d7d00efe5b1/index.spec.ts#L62

If it still doesn't work - could you clarify the version of TypeScript you are using?

**Comment by WestonThayer** [comment]
Good call, it was an issue with my Typescript version. Upgraded to latest and everything is fine.

**Comment by bsalex** [comment]
@WestonThayer 
I've reproduced the problem you described with typescript in strict mode.
The issue has been fixed here: https://github.com/bsalex/typed-path/commit/0f6d6bbe8ee1ddf9f416bb3216a2d8712f81ca9a
Please check version 2.1.2
